exp_name: "lb_up_245"
languages: ["lb"]     # which prefixes to load
domains:  ["news", "gov", "social", "spoken", "web"]  # optional filter
token_targets:
  lb: 245000000 
w2v:
  vector_size: 300
  window: 5
  min_count: 5
  sg: 1          # 1 = skip-gram, 0 = CBOW
  negative: 10
  epochs: 10
  workers: 8
analysis:
  num_clusters: 20
  sample_size: 10000       # words to subsample for clustering
