exp_name: "lb_var_aligned"
languages: ["lb"]
domains:  ["news", "gov", "social", "spoken", "web", "var"]  # optional filter
w2v:
  vector_size: 300
  window: 5
  min_count: 5
  sg: 0          # 1 = skip-gram, 0 = CBOW
  negative: 10
  epochs: 10
  workers: 8
analysis:
  num_clusters: 20
  sample_size: 10000 
